### ISSUE TITLE
unionid as user id not working

### ISSUE THREAD

**Issue by shen0100** [SocialiteProviders/WeChatServiceAccount#1]
Still get openid as user id

**Comment by sinkcup** [comment]
set the config like this:

```
WECHAT_WEB_APP_ID=wx213
WECHAT_WEB_APP_SECRET=asdf
WECHAT_WEB_CALLBACK_URL="http://example.com/login/wechat-web/callback"
WECHAT_WEB_SCOPES=unionid
WECHAT_WEB_UNION_ID_WITH=wechat_service_account,wechat_mini_program
```

docs:

- Chinese https://sinkcup.github.io/laravel-socialite-wechat-login
- English https://laravel-socialite-providers.github.io/providers/wechat-service-account/
